--Q1. What is the total revenue generated by male vs. female customers?
select sum(purchase_amount_usd) as total_revenue,gender
from `customerbehavior.customer_behavior.customer`
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
with cte as(
  select *, round(avg(purchase_amount_usd) over(),2) as average_purchase_amt
  from `customerbehavior.customer_behavior.customer`
)
select customer_id,purchase_amount_usd
from cte
where discount_applied="Yes" and purchase_amount_usd>=average_purchase_amt;

-- Q3. Which are the top 5 products with the highest average review rating?
with cte as (
  select item_purchased,category,round(avg(review_rating),2) as average_review_rating
  from `customerbehavior.customer_behavior.customer`
  group by item_purchased,category
),
rank_no as(
  select *,dense_rank() over(order by average_review_rating desc) as ranking
  from cte
)
select item_purchased,category,average_review_rating,
from rank_no
where ranking<=5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount_usd),2) as average_purchase_amt
from `customerbehavior.customer_behavior.customer`
where shipping_type in ("Standard","Express")
group by shipping_type
order by average_purchase_amt desc;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_cust ,round(avg(purchase_amount_usd),2) as average_spend , sum(purchase_amount_usd) as total_revenue
from `customerbehavior.customer_behavior.customer`
group by subscription_status
order by average_spend desc, total_revenue desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
round(sum(case when lower(discount_applied)="yes" then 1 else 0 end)/count(*) *100,2) as discount_rate
from `customerbehavior.customer_behavior.customer`
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with cust_seg as (select customer_id,previous_purchases,
case
when previous_purchases=1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal"
end as customer_segment
from `customerbehavior.customer_behavior.customer`)

select customer_segment,count(customer_id) as no_of_customers
from cust_seg
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category?
with product_count as(
  select category,item_purchased, count(*) as count_product
  from `customerbehavior.customer_behavior.customer`
  group by category,item_purchased
),
rank_product as(
  select category,item_purchased,count_product,
  row_number() over(partition by category order by count_product desc) as ranking
  from product_count
)
select category,item_purchased,count_product 
from rank_product
where ranking<=3
order by category,ranking;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
with repeat_cust as(select customer_id,subscription_status,previous_purchases
from `customerbehavior.customer_behavior.customer`
where previous_purchases>5)
select subscription_status,count(distinct customer_id) as cust_count
from repeat_cust
group by subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount_usd) as revenue
from `customerbehavior.customer_behavior.customer`
group by age_group
order by revenue desc;


